---
title: "Swedish regional accounts"
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: flatly
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggiraph)
library(glue)
library(scales)
library(shiny)
library(cowplot)
library(sf)

theme_set(theme_light())

df <- read_rds("df.rds")
lan_map_24 <- read_rds("Sweden-24-counties.rds")

```

# Share of GDP by county


Column {data-width=300}
-----------------------------------------------------------------------

### Regional GDP has become less polarized over time in Sweden

Use the slider below to select the year. As we move from 1750 to 1850, the relative share of GDP of Stockholms län falls from more than twice the next largest share to just 25 percent larger than the next largest share.

```{r}
sliderInput("year_c3", label = "Year:",
            min = 1750, max = 1850, value = 1750, step = 10)
```

Column {data-width=900}
-----------------------------------------------------------------------

```{r}
renderGirafe({
  s_map_2 <- lan_map_24 %>%
    inner_join(df %>% filter(
      series == "Shares of total GDP in the Swedish counties (1750-1850)",
      year == input$year_c3
    )) %>%
    mutate( # JavaScript call to open website
      onclick = glue::glue(
        'window.open("https://en.wikipedia.org/wiki/{lan}")'
      )
    ) %>%
    ggplot() +
    geom_sf_interactive(
      aes(
        fill = value,
        data_id = lan,
        tooltip = lan,
        onclick = onclick
      )
    ) +
    scale_fill_gradient2_interactive(
      low = "blue",
      high = "red",
      mid = "pink",
      midpoint = 0.06,
      labels = percent_format()
    ) +
    labs(title = glue("Share of GDP in {input$year_c3}"),
         fill = NULL) +
    theme_void()

  chart_col <- df %>%
    filter(
      series == "Shares of total GDP in the Swedish counties (1750-1850)",
      year == input$year_c3
    ) %>%
    mutate(lan = fct_reorder(lan, value)) %>%
    ggplot(aes(value, lan, fill = value)) +
    geom_col_interactive(aes(data_id = lan, tooltip = lan), show.legend = F) +
    scale_x_continuous(labels = percent_format()) +
    scale_fill_gradient2_interactive(
      low = "blue",
      high = "red",
      mid = "pink",
      midpoint = 0.05,
      labels = percent_format()
    ) +
    labs(
      x = NULL,
      y = NULL
    )

  int_fig_2 <- girafe(
    ggobj = plot_grid(chart_col, s_map_2, rel_widths = c(1, 1), ncol = 2),
    width_svg = 8,
    height_svg = 4,
    options = list(
      # opts_tooltip(css = tooltip_css, delay_mouseover = 0, delay_mouseout = 0),
      opts_hover_inv(css = "opacity:0.1;"),
      opts_hover(css = "stroke-width:2;")
    )
  )

  int_fig_2
})
```

# GDP per capita

```{r}
renderGirafe({
    s_map <- lan_map_24 %>%
    mutate( # JavaScript call to open website
      onclick = glue::glue(
        'window.open("https://en.wikipedia.org/wiki/{lan}")'
      )
    ) %>%
    ggplot() +
    geom_sf_interactive(
      aes(
        data_id = lan,
        tooltip = lan,
        onclick = onclick
      )
    ) +
    theme_void()

  gg <- df %>%
    filter(series == "GDP per capita in the Swedish counties (1750-1850, Sweden=100)") %>%
    ggplot(aes(year, value, color = lan)) +
    geom_line_interactive(aes(tooltip = lan, data_id = lan)) +
    scale_y_continuous(labels = number_format()) +
    scale_color_viridis_d() +
    theme(legend.position = "none") +
    labs(
      y = "GDP per capita (Sweden 1750 = 100)",
      x = NULL
    )

  int_fig <- girafe(
    ggobj = plot_grid(gg, s_map, rel_widths = c(4, 1), ncol = 2),
    width_svg = 5,
    height_svg = 3,
    options = list(
      # opts_tooltip(css = tooltip_css, delay_mouseover = 0, delay_mouseout = 0),
      opts_hover_inv(css = "opacity:0.1;"),
      opts_hover(css = "stroke-width:2;")
    )
  )

  int_fig
})
```

===========================

# Share of value added by sector

Column {data-width=300}
-----------------------------------------------------------------------

### Sectoral specialization over time

Use the slider below to select year. We can observe that over time, Stockholms län became increasingly specialized in manufacturing, while the counties rich in iron ore specialized in mining. 

```{r}
sliderInput("year_c4", label = "Year:",
            min = 1750, max = 1850, value = 1750, step = 10)
```


Column {data-width=900}
-----------------------------------------------------------------------



```{r}

renderGirafe({
    
  s_map_sector <- df %>%
    filter(
      series == "Shares of value added by sector in the Swedish counties, (1750-1850)",
      year != 1769,
      year == input$year_c4
    ) %>%
    select(lan, year, subset, value) %>%
    pivot_wider(names_from = year, values_from = value, values_fill = 0) %>%
    pivot_longer(-c(lan, subset), names_to = "year") %>%
    inner_join(lan_map_24) %>%
    ggplot() +
    geom_sf_interactive(aes(tooltip = lan, geometry = geometry, fill = value)) +
    facet_wrap(~subset) +
    scale_fill_gradient2_interactive(
      low = "blue",
      high = "red",
      mid = "pink",
      midpoint = 0.4,
      labels = percent_format()
    ) +
    theme_void() +
    theme(legend.position = "bottom") +
    guides(fill = guide_colourbar(barwidth = 22, barheight = 1)) +
    labs(title = glue("Share of value added by sector in {input$year_c4}"),
         fill = NULL)
    
    girafe(
    ggobj = s_map_sector,
    width_svg = 6,
    height_svg = 4
  )
})


```

# Labour force

Column {data-width=300}
-----------------------------------------------------------------------

### Diversification out of Agriculture

While in 1750 many counties saw high shares of the labour force in agriculture, in Stockholms län already less than half of the working population worked in agriculture.

Select the different sectors from the dropdown box.

```{r}
selectizeInput("sector_c1", label = "Sector:",
            choices = c("Agriculture", "Manufacturing", "Mining"), 
            selected = "Agriculture",
            multiple = F)

```


Column {data-width=900}
-----------------------------------------------------------------------


```{r}

renderGirafe({
  gg <- df %>%
    filter(
      series == "Labour force shares in the Swedish counties",
      subset == input$sector_c1,
      year != 1769
    ) %>%
    ggplot(aes(year, value, color = lan)) +
    geom_line_interactive(aes(tooltip = lan, data_id = lan)) +
    scale_y_continuous(labels = percent_format()) +
    scale_color_viridis_d() +
    theme(legend.position = "none") +
    labs(
      y = glue("Share of labour force in {input$sector_c1}"),
      x = NULL
    )


  x <- girafe(
    ggobj = gg, width_svg = 6, height_svg = 4,
    options = list(
      opts_hover_inv(css = "opacity:0.1;"),
      opts_hover(css = "stroke-width:2;")
    )
  )

  x
})

```

# Population and output

```{r}

renderGirafe({
  chart_pop_gdp <- df %>%
    filter(series %in% c("Population in the Swedish counties", "GDP per capita in the Swedish counties (1750-1850, Sweden=100)", "Shares of total GDP in the Swedish counties (1750-1850)")) %>%
    select(-subset, -source) %>%
    mutate(series = case_when(
      series == "GDP per capita in the Swedish counties (1750-1850, Sweden=100)" ~ "GDP per capita",
      series == "Population in the Swedish counties" ~ "Population",
      series == "Shares of total GDP in the Swedish counties (1750-1850)" ~ "Share of GDP"
    )) %>%
    ggplot(aes(year, value, colour = lan)) +
    geom_line_interactive(aes(tooltip = lan, data_id = lan), show.legend = F) +
    facet_wrap(~series, scales = "free_y", nrow = 1) +
    scale_y_continuous(labels = number_format()) +
    scale_colour_viridis_d_interactive() +
    labs(
      x = NULL,
      y = NULL
    )

  girafe(
    ggobj = chart_pop_gdp,
    width_svg = 6,
    height_svg = 4,
    options = list(
      # opts_tooltip(css = tooltip_css, delay_mouseover = 0, delay_mouseout = 0),
      opts_hover_inv(css = "opacity:0.1;"),
      opts_hover(css = "stroke-width:2;")
    )
  )
})
```

# Data table

```{r}
    df %>%
      filter(series %in% c("Population in the Swedish counties", "GDP per capita in the Swedish counties (1750-1850, Sweden=100)", "Shares of total GDP in the Swedish counties (1750-1850)")) %>%
      select(-subset, -source) %>%
      mutate(series = case_when(
        series == "GDP per capita in the Swedish counties (1750-1850, Sweden=100)" ~ "GDP per capita",
        series == "Population in the Swedish counties" ~ "Population",
        series == "Shares of total GDP in the Swedish counties (1750-1850)" ~ "Share of GDP"
      )) %>%
      pivot_wider(names_from = series, values_from = value) %>%
      mutate(
        `Share of GDP` = percent(`Share of GDP`, accuracy = .1),
        Population = format(Population, big.mark = " ")
      ) %>%
      arrange(year) %>%
      DT::datatable(rownames = F)


```

